CANONICAL_COLUMNS = [
    "date",
    "description",
    "payee",
    "vendor",
    "notes",
    "amount",
    "debit",
    "credit",
    "balance",
    "category",
    "account",
    "transaction_id",
]

COLUMN_ALIASES = {
    "date": ["date", "txn date", "transaction date", "posted date"],
    "description": ["description", "details", "narrative", "item description"],
    "payee": ["payee", "merchant", "counterparty", "name"],
    "vendor": ["vendor", "supplier"],
    "notes": ["memo", "note", "notes", "reference"],
    "amount": ["amount", "value", "total", "transaction amount"],
    "debit": ["debit", "withdrawal", "outflow", "charge"],
    "credit": ["credit", "deposit", "inflow", "payment"],
    "balance": ["balance", "running balance", "acct balance"],
    "category": ["category", "class", "expense type"],
    "account": ["account", "account name", "gl account"],
    "transaction_id": ["transaction id", "txn id", "id", "reference id", "check #"],
}

STANDARD_ROW_FIELDS = [
    "row_id",
    "source_row_index",
    "date",
    "description",
    "payee",
    "amount",
    "debit",
    "credit",
    "category",
    "account",
    "notes",
    "flags",
    "cleaned_values",
    "original_values",
    "review_status",
]
